<?php
require_once __DIR__ . '/../controllers/AuthController.php';
require_once __DIR__ . '/../controllers/UsuarioController.php';
require_once __DIR__ . '/../Modules/Caja/Controllers/CajaController.php';
require_once __DIR__ . '/../Modules/Caja/Controllers/OperativaController.php';
require_once __DIR__ . '/../controllers/CatalogoController.php';
require_once __DIR__ . '/../controllers/CampoController.php';
require_once __DIR__ . '/../controllers/CpanelController.php';
require_once __DIR__ . '/../controllers/ReporteController.php';
require_once __DIR__ . '/../controllers/OperacionController.php';
require_once __DIR__ . '/../Modules/Evaluacion/Controllers/EvaluacionController.php';
require_once __DIR__ . '/../Modules/Evaluacion/Controllers/DocumentoController.php';
require_once __DIR__ . '/../controllers/HealthController.php';
require_once __DIR__ . '/../Modules/Sucursales/Controllers/SucursalController.php';
require_once __DIR__ . '/../Modules/Rbac/Controllers/RbacController.php';
require_once __DIR__ . '/../Modules/Clientes/Controllers/ClienteController.php';
require_once __DIR__ . '/../Modules/Clientes/Controllers/RegistroClienteController.php';
require_once __DIR__ . '/../Modules/Clientes/Controllers/ClasificacionController.php';
require_once __DIR__ . '/../Modules/Clientes/Controllers/CartaController.php';
require_once __DIR__ . '/../Modules/Creditos/Controllers/CreditoController.php';
require_once __DIR__ . '/../Modules/Creditos/Controllers/CobroController.php';
require_once __DIR__ . '/../Modules/Creditos/Controllers/MoraController.php';
require_once __DIR__ . '/../services/AvanceService.php';
require_once __DIR__ . '/../services/GerenciaService.php';

return function (Router $r) {
    $r->add('GET', '/', HealthController::class, 'index');
    $r->add('GET', '/api', HealthController::class, 'index');
    $r->add('GET', '/api/health', HealthController::class, 'health');
    $r->add('POST', '/api/auth/login', AuthController::class, 'login');
    $r->add('POST', '/api/auth/logout', AuthController::class, 'logout');
    $r->add('GET', '/api/auth/me', AuthController::class, 'me');
    $r->add('GET', '/api/caja/estado', CajaController::class, 'estado');
    $r->add('GET', '/api/usuarios', UsuarioController::class, 'list');
    $r->add('POST', '/api/usuarios/reset', UsuarioController::class, 'resetPassword');
    $r->add('POST', '/api/usuarios/toggle', UsuarioController::class, 'toggleEstado');
    $r->add('POST', '/api/usuarios/actualizar', UsuarioController::class, 'update');
    $r->add('POST', '/api/usuarios', UsuarioController::class, 'create');
    // Módulo Clientes — ver backend/Modules/Clientes/
    (require __DIR__ . '/../Modules/Clientes/routes.php')($r);
    // Módulo Créditos (cobros incluidos) — ver backend/Modules/Creditos/
    (require __DIR__ . '/../Modules/Creditos/routes.php')($r);
    $r->add('POST', '/api/ahorros/anular', AhorroController::class, 'anular');
    $r->add('POST', '/api/ahorros', AhorroController::class, 'registrar');
    $r->add('POST', '/api/metas/eliminar', MetaController::class, 'eliminar');
    $r->add('GET', '/api/metas', MetaController::class, 'listar');
    $r->add('POST', '/api/metas/actualizar', MetaController::class, 'actualizar');
    $r->add('POST', '/api/metas', MetaController::class, 'crear');
    $r->add('POST', '/api/justificaciones/eliminar', JustificacionController::class, 'eliminar');
    $r->add('POST', '/api/justificaciones/actualizar', JustificacionController::class, 'actualizar');
    $r->add('POST', '/api/justificaciones', JustificacionController::class, 'crear');
    $r->add('POST', '/api/adjuntos/subir', AdjuntoController::class, 'subir');
    $r->add('POST', '/api/adjuntos/eliminar', AdjuntoController::class, 'eliminar');
    $r->add('POST', '/api/adjuntos', AdjuntoController::class, 'crear');
    $r->add('GET', '/api/relaciones', RelacionController::class, 'list');
    $r->add('POST', '/api/relaciones/eliminar', RelacionController::class, 'delete');
    $r->add('POST', '/api/relaciones', RelacionController::class, 'add');
    $r->add('GET', '/api/oficinas', OficinaController::class, 'list');
    $r->add('GET', '/api/propuestas/detalle', PropuestaController::class, 'detalle');
    $r->add('GET', '/api/propuestas', PropuestaController::class, 'list');
    $r->add('POST', '/api/propuestas/responder', PropuestaController::class, 'responder');
    $r->add('POST', '/api/cobros/simular', CobroController::class, 'simular');
    $r->add('GET', '/api/adjuntos', AdjuntoController::class, 'listar');
    $r->add('POST', '/api/usuarios/avatar', UsuarioController::class, 'avatar');
    $r->add('POST', '/api/usuarios/eliminar-avatar', UsuarioController::class, 'eliminarAvatar');
    $r->add('POST', '/api/usuarios/mi-perfil', UsuarioController::class, 'miPerfil');
    $r->add('POST', '/api/usuarios/cambiar-clave', UsuarioController::class, 'cambiarClave');
    $r->add('GET', '/api/metas/por-usuario', MetaController::class, 'porUsuario');
    $r->add('POST', '/api/propuestas/eliminar', PropuestaController::class, 'eliminar');
    $r->add('POST', '/api/propuestas/evaluar', PropuestaController::class, 'evaluar');
    $r->add('POST', '/api/caja/cerrar', CajaController::class, 'cerrar');
    $r->add('GET', '/api/boveda/saldos', BovedaController::class, 'saldos');
    $r->add('POST', '/api/boveda/consumir', BovedaController::class, 'consumir');
    $r->add('POST', '/api/boveda/designar', BovedaController::class, 'designar');
    $r->add('GET', '/api/reportes/moras-dias', ReporteController::class, 'morasPorDias');
    $r->add('GET', '/api/reportes/sentinel', ReporteController::class, 'sentinel');
    $r->add('GET', '/api/reportes/cancelados', ReporteController::class, 'cancelados');
    $r->add('GET', '/api/reportes/sin-creditos', ReporteController::class, 'sinCreditos');
    $r->add('GET', '/api/reportes/vinculaciones', ReporteController::class, 'vinculaciones');
    $r->add('GET', '/api/campo/credit-to-pay', CampoController::class, 'creditToPay');
    $r->add('GET', '/api/campo/cobros-hoy', CampoController::class, 'cobrosHoy');
    $r->add('GET', '/api/campo/cobros-realizados', CampoController::class, 'cobrosRealizados');
    $r->add('GET', '/api/util/dni', DniController::class, 'consultar');
    $r->add('GET', '/api/util/distritos', UbigeoController::class, 'distritos');
    $r->add('GET', '/api/util/provincias', UbigeoController::class, 'provincias');
    $r->add('GET', '/api/util/departamentos', UbigeoController::class, 'departamentos');
    $r->add('GET', '/api/formatos/contrato', FormatoController::class, 'contrato');
    $r->add('GET', '/api/cpanel/resumen', CpanelController::class, 'resumen');
    $r->add('GET', '/api/empresa', EmpresaController::class, 'ver');
    $r->add('POST', '/api/empresa/actualizar', EmpresaController::class, 'actualizar');
    $r->add('GET', '/api/reportes/proyecciones', ReporteController::class, 'proyecciones');
    $r->add('GET', '/api/reportes/ahorros-fecha', ReporteController::class, 'ahorrosPorFecha');
    $r->add('GET', '/api/reportes/eliminados', ReporteController::class, 'eliminados');
    $r->add('GET', '/api/ahorros/detalle', AhorroController::class, 'detalle');
    $r->add('GET', '/api/propuestas/detalle', PropuestaController::class, 'detalle');
    $r->add('POST', '/api/propuestas/crear', PropuestaController::class, 'crear');
    $r->add('GET', '/api/reportes/cobros', ReporteController::class, 'cobrosPorFecha');
    $r->add('GET', '/api/reportes/desembolsos', ReporteController::class, 'desembolsosPorFecha');
    $r->add('GET', '/api/reportes/cierre', ReporteController::class, 'cierre');
    // Módulo Caja (caja/bóveda/billetaje/recibos/extornos) — ver backend/Modules/Caja/
    (require __DIR__ . '/../Modules/Caja/routes.php')($r);
    $r->add('GET', '/api/justificaciones', JustificacionController::class, 'listar');
    // Módulo evaluador + documentos — ver backend/Modules/Evaluacion/
    (require __DIR__ . '/../Modules/Evaluacion/routes.php')($r);
    // Módulo sucursales — ver backend/Modules/Sucursales/
    (require __DIR__ . '/../Modules/Sucursales/routes.php')($r);
    // RBAC — ver backend/Modules/Rbac/
    (require __DIR__ . '/../Modules/Rbac/routes.php')($r);
    // Spec 2026: avance/gerencia (caja segura vive en su módulo)
    $r->add('GET', '/api/cobros/avance', AvanceController::class, 'ver');
    $r->add('POST', '/api/cobros/avance/guardar', AvanceController::class, 'guardar');
    $r->add('GET', '/api/cobros/avance/snapshot', AvanceController::class, 'snapshot');
    $r->add('GET', '/api/gerencia/sucursales', GerenciaController::class, 'sucursales');
};
